language: java

jdk:
  - oraclejdk8
  
before_install:
  - curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
  - sudo apt-get install -y nodejs easy_install
  - sudo easy_install pip
  - sudo pip install -r python/requirements.txt
  
install:
  - cd nodejs; npm install; cd ../
  - npm install

script: grunt
