language: java

jdk:
  - oraclejdk8
  
before_install:
  - curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
  - sudo apt-get install -y nodejs
  
install:
  - cd nodejs; npm install; cd ../
  - npm install
  
script: grunt
